name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      with:
        private-key: ${{ secrets.SERVER_SSH_KEY }}
        public-key: ${{ secrets.SSH_KEY_PUBLIC }}
        name: id_rsa # optional
    - name: rsync over ssh
      run: rsync ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{secrets.REMOTE_TARGET }}
